/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TaxRouteImport } from './routes/tax'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProposalRouteImport } from './routes/proposal'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as MarketDataRouteImport } from './routes/market-data'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'

const TaxRoute = TaxRouteImport.update({
  id: '/tax',
  path: '/tax',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalRoute = ProposalRouteImport.update({
  id: '/proposal',
  path: '/proposal',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketDataRoute = MarketDataRouteImport.update({
  id: '/market-data',
  path: '/market-data',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/market-data': typeof MarketDataRoute
  '/portfolio': typeof PortfolioRoute
  '/proposal': typeof ProposalRoute
  '/reports': typeof ReportsRoute
  '/tax': typeof TaxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/market-data': typeof MarketDataRoute
  '/portfolio': typeof PortfolioRoute
  '/proposal': typeof ProposalRoute
  '/reports': typeof ReportsRoute
  '/tax': typeof TaxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/market-data': typeof MarketDataRoute
  '/portfolio': typeof PortfolioRoute
  '/proposal': typeof ProposalRoute
  '/reports': typeof ReportsRoute
  '/tax': typeof TaxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/market-data'
    | '/portfolio'
    | '/proposal'
    | '/reports'
    | '/tax'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/market-data'
    | '/portfolio'
    | '/proposal'
    | '/reports'
    | '/tax'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/market-data'
    | '/portfolio'
    | '/proposal'
    | '/reports'
    | '/tax'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  MarketDataRoute: typeof MarketDataRoute
  PortfolioRoute: typeof PortfolioRoute
  ProposalRoute: typeof ProposalRoute
  ReportsRoute: typeof ReportsRoute
  TaxRoute: typeof TaxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tax': {
      id: '/tax'
      path: '/tax'
      fullPath: '/tax'
      preLoaderRoute: typeof TaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal': {
      id: '/proposal'
      path: '/proposal'
      fullPath: '/proposal'
      preLoaderRoute: typeof ProposalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-data': {
      id: '/market-data'
      path: '/market-data'
      fullPath: '/market-data'
      preLoaderRoute: typeof MarketDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  MarketDataRoute: MarketDataRoute,
  PortfolioRoute: PortfolioRoute,
  ProposalRoute: ProposalRoute,
  ReportsRoute: ReportsRoute,
  TaxRoute: TaxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
