/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TaxRouteImport } from './routes/tax'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProposalRouteImport } from './routes/proposal'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as MarketDataRouteImport } from './routes/market-data'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantIndexRouteImport } from './routes/assistant.index'
import { Route as DebugLogsRouteImport } from './routes/debug.logs'
import { Route as AssistantThreadIdRouteImport } from './routes/assistant.$threadId'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPublicDebugLogsRouteImport } from './routes/api/public/debug-logs'

const TaxRoute = TaxRouteImport.update({
  id: '/tax',
  path: '/tax',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalRoute = ProposalRouteImport.update({
  id: '/proposal',
  path: '/proposal',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketDataRoute = MarketDataRouteImport.update({
  id: '/market-data',
  path: '/market-data',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantIndexRoute = AssistantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AssistantRoute,
} as any)
const DebugLogsRoute = DebugLogsRouteImport.update({
  id: '/debug/logs',
  path: '/debug/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantThreadIdRoute = AssistantThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => AssistantRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDebugLogsRoute = ApiPublicDebugLogsRouteImport.update({
  id: '/api/public/debug-logs',
  path: '/api/public/debug-logs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRouteWithChildren
  '/market-data': typeof MarketDataRoute
  '/portfolio': typeof PortfolioRoute
  '/proposal': typeof ProposalRoute
  '/reports': typeof ReportsRoute
  '/tax': typeof TaxRoute
  '/api/chat': typeof ApiChatRoute
  '/assistant/$threadId': typeof AssistantThreadIdRoute
  '/debug/logs': typeof DebugLogsRoute
  '/assistant/': typeof AssistantIndexRoute
  '/api/public/debug-logs': typeof ApiPublicDebugLogsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/market-data': typeof MarketDataRoute
  '/portfolio': typeof PortfolioRoute
  '/proposal': typeof ProposalRoute
  '/reports': typeof ReportsRoute
  '/tax': typeof TaxRoute
  '/api/chat': typeof ApiChatRoute
  '/assistant/$threadId': typeof AssistantThreadIdRoute
  '/debug/logs': typeof DebugLogsRoute
  '/assistant': typeof AssistantIndexRoute
  '/api/public/debug-logs': typeof ApiPublicDebugLogsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRouteWithChildren
  '/market-data': typeof MarketDataRoute
  '/portfolio': typeof PortfolioRoute
  '/proposal': typeof ProposalRoute
  '/reports': typeof ReportsRoute
  '/tax': typeof TaxRoute
  '/api/chat': typeof ApiChatRoute
  '/assistant/$threadId': typeof AssistantThreadIdRoute
  '/debug/logs': typeof DebugLogsRoute
  '/assistant/': typeof AssistantIndexRoute
  '/api/public/debug-logs': typeof ApiPublicDebugLogsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/assistant'
    | '/market-data'
    | '/portfolio'
    | '/proposal'
    | '/reports'
    | '/tax'
    | '/api/chat'
    | '/assistant/$threadId'
    | '/debug/logs'
    | '/assistant/'
    | '/api/public/debug-logs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/market-data'
    | '/portfolio'
    | '/proposal'
    | '/reports'
    | '/tax'
    | '/api/chat'
    | '/assistant/$threadId'
    | '/debug/logs'
    | '/assistant'
    | '/api/public/debug-logs'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/analytics'
    | '/assistant'
    | '/market-data'
    | '/portfolio'
    | '/proposal'
    | '/reports'
    | '/tax'
    | '/api/chat'
    | '/assistant/$threadId'
    | '/debug/logs'
    | '/assistant/'
    | '/api/public/debug-logs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AssistantRoute: typeof AssistantRouteWithChildren
  MarketDataRoute: typeof MarketDataRoute
  PortfolioRoute: typeof PortfolioRoute
  ProposalRoute: typeof ProposalRoute
  ReportsRoute: typeof ReportsRoute
  TaxRoute: typeof TaxRoute
  ApiChatRoute: typeof ApiChatRoute
  DebugLogsRoute: typeof DebugLogsRoute
  ApiPublicDebugLogsRoute: typeof ApiPublicDebugLogsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tax': {
      id: '/tax'
      path: '/tax'
      fullPath: '/tax'
      preLoaderRoute: typeof TaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal': {
      id: '/proposal'
      path: '/proposal'
      fullPath: '/proposal'
      preLoaderRoute: typeof ProposalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-data': {
      id: '/market-data'
      path: '/market-data'
      fullPath: '/market-data'
      preLoaderRoute: typeof MarketDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant/': {
      id: '/assistant/'
      path: '/'
      fullPath: '/assistant/'
      preLoaderRoute: typeof AssistantIndexRouteImport
      parentRoute: typeof AssistantRoute
    }
    '/debug/logs': {
      id: '/debug/logs'
      path: '/debug/logs'
      fullPath: '/debug/logs'
      preLoaderRoute: typeof DebugLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant/$threadId': {
      id: '/assistant/$threadId'
      path: '/$threadId'
      fullPath: '/assistant/$threadId'
      preLoaderRoute: typeof AssistantThreadIdRouteImport
      parentRoute: typeof AssistantRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/debug-logs': {
      id: '/api/public/debug-logs'
      path: '/api/public/debug-logs'
      fullPath: '/api/public/debug-logs'
      preLoaderRoute: typeof ApiPublicDebugLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AssistantRouteChildren {
  AssistantThreadIdRoute: typeof AssistantThreadIdRoute
  AssistantIndexRoute: typeof AssistantIndexRoute
}

const AssistantRouteChildren: AssistantRouteChildren = {
  AssistantThreadIdRoute: AssistantThreadIdRoute,
  AssistantIndexRoute: AssistantIndexRoute,
}

const AssistantRouteWithChildren = AssistantRoute._addFileChildren(
  AssistantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  AssistantRoute: AssistantRouteWithChildren,
  MarketDataRoute: MarketDataRoute,
  PortfolioRoute: PortfolioRoute,
  ProposalRoute: ProposalRoute,
  ReportsRoute: ReportsRoute,
  TaxRoute: TaxRoute,
  ApiChatRoute: ApiChatRoute,
  DebugLogsRoute: DebugLogsRoute,
  ApiPublicDebugLogsRoute: ApiPublicDebugLogsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
